
name: Run Cypress Tests Daily

on:
  schedule:
    - cron: '30 14 * * *' # Runs at 8:00 PM IST (14:30 UTC) every day
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  cypress-run:
    environment: .env.dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'


      - name: Install dependencies
        run: npm ci

      - name: Install Cypress binary
        run: npx cypress install

      - name: Run Cypress tests
        run: npm run test:ci
        env:
          RS_USER: ${{ secrets.RS_USER }}
          RS_PASS: ${{ secrets.RS_PASS }}
          RS_WORKSPACE: ${{ secrets.RS_WORKSPACE }}

      - name: Upload Cypress screenshots (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots


      - name: Upload Cypress videos (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload test-config.json
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-config-${{ github.run_id }}
          path: cypress/fixtures/test-config.json

      - name: Upload eventsDeliveryCount.json
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eventsDeliveryCount-${{ github.run_id }}
          path: cypress/fixtures/eventsDeliveryCount.json

      - name: Generate Cypress Test Report
        if: always()
        run: |
          echo "## Cypress Test Report" >> $GITHUB_STEP_SUMMARY
          echo "Workflow completed at: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "Artifacts uploaded:" >> $GITHUB_STEP_SUMMARY
          echo "Screenshots, Videos, test-config.json, eventsDeliveryCount.json can be found in the workflow run artifacts." >> $GITHUB_STEP_SUMMARY
      
      - name: Upload Mochawesome HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report-${{ github.run_id }}
          path: cypress/reports/*.html
